version: '3.8'

services:
  poll:
    build:
      context: ./poll
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:alpine

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
