# Utiliser une image de base avec Java
FROM openjdk:11-jre-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier l'application Java compilée dans le conteneur
COPY target/worker.jar .

# Définir la commande par défaut pour exécuter l'application Java
CMD ["java", "-jar", "worker.jar"]
