# Utiliser une image de base avec Python
FROM python:3.9-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les dépendances de l'application et installer les paquets Python nécessaires
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste de l'application dans le conteneur
COPY . .

# Définir la commande par défaut pour exécuter l'application Flask
CMD ["python", "poll.py"]
