# Utiliser l'image Python officielle
FROM python:3.11

# Définir le répertoire de travail dans le conteneur
WORKDIR /poll

# Copier les fichiers de l'application
COPY . .

# Installer les dépendances de l'application
RUN pip3 install -r requirements.txt

# Exposer le port 80
EXPOSE 80

# Commande pour démarrer l'application
CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]
